const PREFIX='kotoba-closet-';
const RELEASE='v9-2765b96ca675';
const CORE_CACHE=PREFIX+RELEASE+'-core';
const MEDIA_CACHE=PREFIX+RELEASE+'-media';
const MEDIA_LIMIT=160;
// Regenerated by node scripts/build-offline-core.mjs.
const CORE=[
 "./",
 "./apple-touch-icon.png",
 "./assets/audio/nanami/08bac1804c0884c1ddf8.mp3",
 "./assets/audio/nanami/0d1936f94462379a5657.mp3",
 "./assets/audio/nanami/136b913c615251af87cc.mp3",
 "./assets/audio/nanami/1d0f55de951bfbf134c0.mp3",
 "./assets/audio/nanami/29d208cbd05c559e2444.mp3",
 "./assets/audio/nanami/543c7e79876b67013158.mp3",
 "./assets/audio/nanami/545b13d79ed62fc35ebf.mp3",
 "./assets/audio/nanami/573dcf216a73aeb34c4d.mp3",
 "./assets/audio/nanami/72c790dce1daf56798a8.mp3",
 "./assets/audio/nanami/75505786962a0fcc4d3f.mp3",
 "./assets/audio/nanami/8a56590d7675dfa4eb8f.mp3",
 "./assets/audio/nanami/b8ce8cf67ba01a583598.mp3",
 "./assets/audio/nanami/c0958189724166380f23.mp3",
 "./assets/audio/nanami/e4f7d5fa3c1301ab0078.mp3",
 "./assets/audio/nanami/fa21c92100584c92dbd6.mp3",
 "./assets/icons/app-icon-192.png",
 "./assets/icons/app-icon-512.png",
 "./assets/rig/base-face-v19.png",
 "./assets/rig/head-replace-v25.png",
 "./assets/scenes/cafe.jpg",
 "./assets/worn-v18/bottom_pleat/owner.png",
 "./assets/worn-v18/bottom_pleat/sock-cover.png",
 "./assets/worn-v18/bottom_pleat/sock-cutout.png",
 "./assets/worn-v18/bottom_pleat/thumb.webp",
 "./assets/worn-v18/bottom_pleat/worn.webp",
 "./assets/worn-v18/hair_straight_v23/head-thumb-v25.webp",
 "./assets/worn-v18/hair_straight_v23/head-v25.webp",
 "./assets/worn-v18/hair_straight_v23/lengths-back-v25.webp",
 "./assets/worn-v18/hair_straight_v23/lengths-front-v25.webp",
 "./assets/worn-v18/shoes_maryjane_socks_v19/owner.png",
 "./assets/worn-v18/shoes_maryjane_socks_v19/thumb.webp",
 "./assets/worn-v18/shoes_maryjane_socks_v19/worn.webp",
 "./assets/worn-v18/top_blouse/owner.png",
 "./assets/worn-v18/top_blouse/thumb.webp",
 "./assets/worn-v18/top_blouse/worn.webp",
 "./data/advanced-japanese.js",
 "./data/audio-nanami.js",
 "./data/backgrounds.js",
 "./data/batch-items.js",
 "./data/brand-intros.js",
 "./data/complete-v18.js",
 "./data/content.js",
 "./data/everyday.js",
 "./data/fit.js",
 "./data/hairstyles.js",
 "./data/item-descriptions.js",
 "./data/item-vocabulary.js",
 "./data/items-v10.js",
 "./data/items-v15.js",
 "./data/items-v17.js",
 "./data/items-v7.js",
 "./data/production.js",
 "./data/scene-learning.js",
 "./data/scenes.js",
 "./data/wardrobe-expansion.js",
 "./data/wardrobe-order.js",
 "./data/worn-v18.js",
 "./index.html",
 "./manifest.webmanifest",
 "./src/game.js",
 "./src/image-cache.js",
 "./src/learning.js",
 "./src/mobile.js",
 "./src/questions.js",
 "./src/recorded-voice.js",
 "./src/render-plan.js",
 "./src/render-worn-v18.js",
 "./src/storage.js",
 "./src/study-state.js",
 "./src/voice.js",
 "./src/wardrobe-state.js",
 "./src/wardrobe.js",
 "./styles/main.css",
 "./styles/mobile.css",
 "./styles/overrides.css",
 "./styles/room.css",
 "./styles/takeover.css",
 "./styles/wardrobe.css"
];
const scope=new URL('./',self.location.href);
const corePaths=new Set(CORE.map(file=>new URL(file,scope).pathname));
let mediaWrites=Promise.resolve();

self.addEventListener('install',event=>{
 event.waitUntil(caches.open(CORE_CACHE).then(cache=>cache.addAll(CORE.map(file=>new Request(new URL(file,scope),{cache:'reload'})))).then(async()=>{
  // v8 clients have no update button; migrate them after this release is complete.
  if((await caches.keys()).includes(PREFIX+'v8'))await self.skipWaiting();
 }));
});
self.addEventListener('activate',event=>{
 event.waitUntil((async()=>{
  const keys=await caches.keys(),legacy=keys.includes(PREFIX+'v8');
  await Promise.all(keys.filter(key=>key.startsWith(PREFIX)&&![CORE_CACHE,MEDIA_CACHE].includes(key)).map(key=>caches.delete(key)));
  await self.clients.claim();
  if(legacy)for(const client of await self.clients.matchAll({type:'window'}))if(new URL(client.url).pathname.startsWith(scope.pathname))await client.navigate(client.url);
 })());
});

function cacheMedia(request,response){
 mediaWrites=mediaWrites.catch(()=>{}).then(async()=>{
  const cache=await caches.open(MEDIA_CACHE);await cache.put(request,response);
  const keys=await cache.keys();await Promise.all(keys.slice(0,Math.max(0,keys.length-MEDIA_LIMIT)).map(key=>cache.delete(key)));
 });
 return mediaWrites;
}
async function rangeResponse(request,response){
 const range=request.headers.get('range');if(!range)return response;
 const match=/^bytes=(\d*)-(\d*)$/.exec(range);if(!match)return response;
 const body=await response.blob(),size=body.size;
 const start=match[1]?Number(match[1]):Math.max(0,size-Number(match[2]));
 const end=match[1]&&match[2]?Math.min(Number(match[2]),size-1):size-1;
 if(start>end||start>=size)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${size}`}});
 const headers=new Headers(response.headers);headers.set('Content-Range',`bytes ${start}-${end}/${size}`);headers.set('Content-Length',String(end-start+1));headers.set('Accept-Ranges','bytes');
 return new Response(body.slice(start,end+1),{status:206,headers});
}
self.addEventListener('fetch',event=>{
 const request=event.request,url=new URL(request.url);
 if(request.method!=='GET'||url.origin!==scope.origin||!url.pathname.startsWith(scope.pathname))return;
 event.respondWith((async()=>{
  // HTML and modules come from one installed release until an update is accepted.
  const core=await caches.open(CORE_CACHE);
  const cached=await core.match(request.mode==='navigate'?new URL('index.html',scope):url,{ignoreSearch:true});
  if(cached&&(request.mode==='navigate'||corePaths.has(url.pathname)))return rangeResponse(request,cached);
  const media=await caches.open(MEDIA_CACHE),asset=await media.match(request,{ignoreSearch:true});
  if(asset)return rangeResponse(request,asset);
  try{
   // Fetch a complete audio file so cached playback also supports iOS Range requests.
   const headers=new Headers(request.headers);headers.delete('range');
   const response=await fetch(new Request(request,{headers}));
   if(response.ok&&response.status===200){const copy=response.clone();event.waitUntil(cacheMedia(new Request(url),copy).catch(()=>{}));}
   return rangeResponse(request,response);
  }catch{return new Response('此内容尚未下载，联网后再试。',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});}
 })());
});
self.addEventListener('message',event=>{
 if(event.data?.type==='SKIP_WAITING'){self.skipWaiting();return;}
 if(event.data?.type!=='CACHE_VISITED')return;
 event.waitUntil((async()=>{
  let complete=true;
  for(const value of (Array.isArray(event.data.urls)?event.data.urls:[]).slice(0,160)){
   try{
    const url=new URL(value,scope);if(url.origin!==scope.origin||!url.pathname.startsWith(new URL('assets/',scope).pathname))continue;
    if(await caches.match(url,{ignoreSearch:true}))continue;
    const response=await fetch(url);if(!response.ok){complete=false;continue;}await cacheMedia(new Request(url),response);
   }catch{complete=false;}
  }
  event.ports[0]?.postMessage({complete});
 })());
});
